--- 
abstract: Perl wrapper for Japanese thesaurus search on labs.tripit.jp.
author: Toru Yamaguchi <zigorou@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WebService-TRIPIT-Thesaurus
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp::Clan: 0
  Class::Accessor::Fast: 0
  Encode: 0
  WWW::REST: 0
  XML::LibXML: 1.62
version: 0.02
